---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hadoop-namenode 
  namespace: hadoop
  annotations:
    volume.beta.kubernetes.io/storage-class: slow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
