---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode 
  namespace: hadoop 
  labels:
    app: hadoop 
    daemon: datanode 
spec:
  ports:
  - port: 50010
    name: datanode
    protocol: TCP
    targetPort: 50010
    nodePort: 30669
  selector:
    app: hadoop
    daemon: datanode 
  type: NodePort 
