---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-httpfs 
  namespace: hadoop 
  labels:
    app: hadoop 
    daemon: httpfs 
spec:
  ports:
  - port: 80
    name: http 
    protocol: TCP
    targetPort: 14000
  selector:
    app: hadoop
    daemon: httpfs 
  type: LoadBalancer
