apiVersion: v1
kind: Service
metadata:
  name: ambari-master
  namespace: bigdata
  labels:
    app: ambari-master
spec:
  type: NodePort
  clusterIP: None
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 31175
  - name: agent
    port: 8440
    targetPort: 8440
  - name: https
    port: 8441
    targetPort: 8441
  selector:
    app: ambari-master
---
apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: ambari-master
  namespace: bigdata
spec:
  serviceName: "ambari-master"
  replicas: 1
  template:
    metadata:
      labels:
        app: ambari-master
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: ambari-master
        image: 10.110.17.138:5000/iop/ambari-server:v2.0
        imagePullPolicy: Always
        command:
           - /usr/local/bin/start.sh
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: agent
          containerPort: 8440
          protocol: TCP
        - name: https
          containerPort: 8441
          protocol: TCP
        securityContext:
          privileged: true
        env:
        - name: AMBARI_SERVER_HOSTNAME
          value: ambari-master-0.ambari-master.bigdata.svc.iopk8s.com

